---
title: "About"
---

The archival doughnut is a visual metaphor fostering a better understanding of the nature, scope, and impact of archival practices on historical records and, subsequently, historical scholarship. It serves the identification of urgent focal points in improving recordkeeping practices while also helping to identify potentially important areas of source-critical reflection in historical scholarship. This relates, in the first place, to the impacts of the actions of the creator of a document, but, more importantly, also to the successive actions that transformations and the eventual nature and form of the document.

The archival doughnut relies on theories, terminologies, methods, and practices of archival science, such as the Records Continuum Model. The goal is not primarily to better understand archival formation as such, but mainly to learn to make better use of the theories and methods from archival science where they can help us to better understand historical records, their provenance, and their context. The doughnut is a conceptual framework that helps looking at how archival formation and practices interact with epistemology and historical knowledge. In this way, the archival doughnut bridges archival theory, practice, and source criticism in historical scholarship.

The doughnut-shaped diagram is based on the work of the English economist Kate Raworth's idea of 'Doughnut Economics'. The visual model consists basically of a pair of concentric rings, where the space between the smaller and the bigger ring, the 'dough' of the doughnut, represents a sweet spot in between shortfall and overshoot. Where, in Raworth's model, this space represents a safe and just space for humanity, the Archival Doughnut's claims are of a more modest nature. Like Raworth's original doughnut, however, the Archival Doughnut is used to serve as a metaphor to help identifying concrete aspects of a complex system that is - often invisible or unconsciously - shaping our thinking and the world around us.

The ‘dough’ of the doughnut represents a varied series of archival practices and activities that contribute to a FAIR and/or CORE way of archiving and opening up historical archival records. The archival doughnut aims to include both the more traditional archival work and practices in the digital realm, e.g., regarding digitisation and the management of retro-digitised records, digital-born data, or online accessibility.

The record-keeping practices and actions in the space within the two concentric rings can be categorised as follows:

• Capture: Gathering, appraisal, collection, acquisition, harvesting, web-crawling, etc.

• Digitise: Scanning, transcription, Automated Text Recognition (ATR).

• Contextualise and structure: Metadata, (linguistic) enrichment, annotation, tagging (e.g., Named Entity Recognition).

• Organise: Appraisal, description, categorisation.

• Pluralise: Access, digital data sets, online access, and (re-)use.

**Outside the ‘dough’**

The model sets the boundaries for minimum requirements in archival practice and identifies where possible overshoot actions lead to unforeseen and/or undesirable outcomes of such practices. This means that the Archival Doughnut also has normative and disciplinary implications, as it can be used to trace archival practices and activities that lead to 'shortfall' or ‘overshoot' conditions that consciously or unconsciously, visibly, and invisibly have the potential to impact, bias, or disturb the organisation, interpretation, or production of historical knowledge.

**'Shortfall'** conditions are represented by the hole in the middle of the metaphorical doughnut. This mostly refers to a lack of or insufficient record-keeping actions. It refers, for example, to the non-existence, loss, obscurity, scarcity, or omission of records. This hole is also called the ‘negative archival landscape’.

‘**Overshoot’** conditions, on the other side of the doughnut, is also important to study, as these consider the critical, undesirable, and potential harmful (side) effects of record-keeping practices. Some overshoot conditions are:

-   The violation of privacy legislation or ethical standards by excessive accessibility provision.

-   Oversimplification or unnecessary reduction of complexity on classification, description, or other ways of structuring data.

-   The unwarranted establishment of connections between record (collections).

﻿The overshoot and shortfall conditions are not absolute values with clearly demarcated and defined criteria; they are relative to the assumptions or starting point of consideration and can thus vary from use case to use case. I consider both the shortfall and the overshoot outliers of the doughnut as guiding, inventorying, and agenda-setting conceptual instruments.

The Archival Doughnut serves as a conceptual tool with normative implications. It assists in making explicit what overshoot or shortfall conditions are, and how both archival practitioners and historical scholars can reflect on them. The model serves as a starting point for identification and reflection of actions within and outside of the doughnut, and how these potentially impact the acquisition, organisation, shaping, interpretation and dissemination of historical knowledge. It is, as such, a starting point for analysing, inventorying, and mapping of key points of what can be called expanded source criticism. I consider both the shortfall and the overshoot outliers of the doughnut as guiding, inventorying, and agenda-setting conceptual instruments.

*Milan van Lange, 2024*
